default:
	@echo targets:  publish publish-video open


publish:
	scp ruth.html paulshannnon@pshannon.net:public_html/pshannon.net/tlingit-demos/
	scp ijal.css paulshannnon@pshannon.net:public_html/pshannon.net/tlingit-demos/
	scp jquery-3.3.1.min.js paulshannnon@pshannon.net:public_html/pshannon.net/tlingit-demos/
	scp ijalUtils.js paulshannnon@pshannon.net:public_html/pshannon.net/tlingit-demos/
	scp audio/* paulshannnon@pshannon.net:public_html/pshannon.net/tlingit-demos/audio

publish-video:
	scp 1RuthNora2Wide.m4v paulshannnon@pshannon.net:public_html/pshannon.net/tlingit-demos

open:
	open https://pshannon.net/tlingit-demos/ruth.html
